version: '3'
services:
  php:
    build: ./php
    image: php
    hostname: php
    container_name: php
    tty: true
    stdin_open: true
    networks:
      react_php_net:
        ipv4_address: 10.20.0.3
    extra_hosts:
      - 'php: 10.20.0.3'
      - 'react: 10.20.0.2'
  react:
    build: ./react
    image: react
    hostname: react
    container_name: react
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    networks:
      react_php_net:
        ipv4_address: 10.20.0.2
    extra_hosts:
      - 'php: 10.20.0.3'
      - 'react: 10.20.0.2'
networks:
  react_php_net:
    name: react_php
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24
